name: Code Integration

on:
  pull_request:
    branches: [main]

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: Build Angular app to prod
        working-directory: angular-mat-todo
        run: npm ci && npm build



